--
-- BORRAR BBDD
--
DROP DATABASE IF EXISTS MEDICAPP;

--
-- CREAR BBDD
--
CREATE DATABASE MEDICAPP
CHARACTER SET utf8
COLLATE utf8_spanish_ci;

USE MEDICAPP;

--
-- Creacion de tablas
--
CREATE TABLE Usuario (
  ID_USUARIO 	INT 		AUTO_INCREMENT,
  USERNAME 		VARCHAR(60) NOT NULL,
  PASSWORD 		VARCHAR(60) NOT NULL,
  NOMBRE 		VARCHAR(60) NOT NULL,
  APELLIDO 		VARCHAR(60) NOT NULL,
  TELEFONO 		VARCHAR(60) NOT NULL,
  DNI 			VARCHAR(60) NOT NULL,
  ROL 			VARCHAR(60) NOT NULL,
  CONSTRAINT	PK_Usuario					PRIMARY KEY (ID_USUARIO)
)ENGINE=INNODB;

CREATE TABLE Medico (
  ID_MEDICO	INT			AUTO_INCREMENT,
  ID_USUARIO 	INT 		NULL,
  CONSTRAINT	PK_Medico				PRIMARY KEY (ID_MEDICO),
  CONSTRAINT 	FK_Usuario2				FOREIGN KEY (ID_USUARIO)
				REFERENCES 					Usuario	(ID_USUARIO)
				ON DELETE CASCADE
				ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE Paciente (
  ID_PACIENTE	INT			AUTO_INCREMENT,
  ID_USUARIO 	INT 		NULL,
  ID_MEDICO 	INT 		NULL,
  DESCRIPCION 		VARCHAR(60) NOT NULL,
  CONSTRAINT	PK_Paciente				PRIMARY KEY (ID_PACIENTE),
  CONSTRAINT 	FK_Medico			FOREIGN KEY (ID_MEDICO)
				REFERENCES 					Medico	(ID_MEDICO),
  CONSTRAINT 	FK_Usuario3			FOREIGN KEY (ID_USUARIO)
				REFERENCES 					Usuario	(ID_USUARIO)
				ON DELETE CASCADE
				ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE Familiar (
  ID_FAMILIAR 	INT			AUTO_INCREMENT,
  ID_USUARIO	INT 		NULL,
  ID_PACIENTE	INT 		NULL,
  CONSTRAINT	PK_Familiar				PRIMARY KEY (ID_FAMILIAR),
  CONSTRAINT 	FK_Usuario				FOREIGN KEY (ID_USUARIO)
				REFERENCES 					Usuario	(ID_USUARIO),
  CONSTRAINT 	FK_Paciente0				FOREIGN KEY (ID_PACIENTE)
				REFERENCES 					Paciente	(ID_PACIENTE)
				ON DELETE CASCADE
				ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE Historial_Medico (
  ID_HISTORIA 	INT			AUTO_INCREMENT,
  ID_PACIENTE	INT 		NULL,
  DESCRIPCION 		VARCHAR(60) NOT NULL,
  FECHA_EVENTO DATE NOT NULL,
  CONSTRAINT	PK_Familiar				PRIMARY KEY (ID_HISTORIA),
  CONSTRAINT 	FK_Paciente				FOREIGN KEY (ID_PACIENTE)
				REFERENCES 					Paciente	(ID_PACIENTE)
				ON DELETE CASCADE
				ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE Temperatura (
  ID_TEMPERATURA 	INT			AUTO_INCREMENT,
  ID_PACIENTE	INT 		NULL,
  FECHA_TEMP 	DATETIME  DEFAULT current_timestamp(),
  TEMPERATURA 			VARCHAR(10) NULL,
  HUMEDAD 		VARCHAR(10) NULL,
  CONSTRAINT	PK_Familiar				PRIMARY KEY (ID_TEMPERATURA),
  CONSTRAINT 	FK_Paciente2				FOREIGN KEY (ID_PACIENTE)
				REFERENCES 					Paciente	(ID_PACIENTE)
				ON DELETE CASCADE
				ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE Movimiento (
  ID_MOVIMIENTO 	INT			AUTO_INCREMENT,
  ID_PACIENTE	INT 		NULL,
  FECHA_EVENTO DATETIME  DEFAULT current_timestamp(),
  SENSOR 		VARCHAR(10) NOT NULL,
  CONSTRAINT	PK_Familiar				PRIMARY KEY (ID_MOVIMIENTO),
  CONSTRAINT 	FK_Paciente3				FOREIGN KEY (ID_PACIENTE)
				REFERENCES 					Paciente	(ID_PACIENTE)
				ON DELETE CASCADE
				ON UPDATE CASCADE
)ENGINE=INNODB;


CREATE TABLE Chat (
  ID_CHAT 	INT 		AUTO_INCREMENT,
  ID_USER_MEDIC INT,
  ID_USER INT,
  CONSTRAINT	PK_Chat					PRIMARY KEY (ID_CHAT)
)ENGINE=INNODB;

CREATE TABLE Mensaje (
  ID_MSG 	INT 		AUTO_INCREMENT,
  ID_CHAT INT,
  USERNAME_SEND VARCHAR(60) NOT NULL,
  MSG VARCHAR(1024) NOT NULL,
  MSG_FECHA 		DATETIME NOT NULL DEFAULT current_timestamp(),
  CONSTRAINT	PK_Mensaje					PRIMARY KEY (ID_MSG),
  CONSTRAINT 	FK_Chat2				FOREIGN KEY (ID_CHAT)
				REFERENCES 					Chat	(ID_CHAT)
				ON DELETE CASCADE
				ON UPDATE CASCADE
)ENGINE=INNODB;


INSERT INTO Usuario values (1,'pepe','1234','Jose','Perez','657345077','3567912V','M');
INSERT INTO Usuario values (2,'rosa','1234','Rosa','Undarigazpi','639301833','34964912X','F');
INSERT INTO Usuario values (3,'javi','1234','Javier','Liebana','647943788','15348677D','P');
INSERT INTO Medico values (1,1);
INSERT INTO Paciente values (1,3,1,'El paciente tiene fiebre');
INSERT INTO Familiar values (1,2,1);



INSERT INTO Usuario values (4,'ana','1234','Ana','Lopez','642893111','17563489F','P');
INSERT INTO Usuario values (5,'paco','1234','Francisco','Gutierrez','687345980','45337845L','F');
INSERT INTO Paciente values (2,4,1,'El paciente esta tieso');
INSERT INTO Familiar values (2,5,1);

INSERT INTO Historial_Medico (ID_PACIENTE,DESCRIPCION,FECHA_EVENTO) values(1,'El paciene se metio un ostiazo','2020-05-19');
INSERT INTO Temperatura (ID_TEMPERATURA,ID_PACIENTE,TEMPERATURA,HUMEDAD)values (1,1,'34','8');
INSERT INTO Movimiento(ID_MOVIMIENTO,ID_PACIENTE,SENSOR) values (1,1,'Puerta Exterior');


INSERT INTO Chat (ID_USER_MEDIC,ID_USER) values (1,3);
INSERT INTO Chat (ID_USER_MEDIC,ID_USER) values (1,2);
INSERT INTO Chat (ID_USER_MEDIC,ID_USER) values (1,4);
INSERT INTO Mensaje (ID_CHAT,USERNAME_SEND,MSG) values (1,'pepe','soy medico');
INSERT INTO Mensaje (ID_CHAT,USERNAME_SEND,MSG) values (1,'javi','soy paciente');
INSERT INTO Mensaje (ID_CHAT,USERNAME_SEND,MSG) values (2,'rosa','Hola esto es un mensaje de familiar a medico');
INSERT INTO Mensaje (ID_CHAT,USERNAME_SEND,MSG) values (2,'pepe','Hola esto es un mensaje de medico a familiar');



